<?php
/**
 * $Id$
 *
 * Copyright (c) 2008-2010 Andreas Heigl<andreas@heigl.org>
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 * THE SOFTWARE.
 *
 * This file has been automaticly created from the file bahyph.tex
 * via the method Org_Heigl_Hyphenator::parseTexFile().
 *
 * DO NOT EDIT THIS FILE EXCEPT YOU KNOW WHAT YOU DO!!
 *
 * @category   Org_Heigl
 * @package    Org_Heigl_Hyphenator
 * @subpackage HyphenationFiles
 * @author     Org_Heigl_Hyphenator
 * @copyright  2008-2010 Andreas Heigl<andreas@heigl.org>
 * @license    http://www.opensource.org/licenses/mit-license.php MIT-License
 * @version    1.0
 * @since      12.09.2011
 */
$pattern['ba'] = '100';
$pattern['be'] = '100';
$pattern['bo'] = '100';
$pattern['bi'] = '100';
$pattern['bu'] = '100';
$pattern['ca'] = '100';
$pattern['ce'] = '100';
$pattern['co'] = '100';
$pattern['ci'] = '100';
$pattern['cu'] = '100';
$pattern['da'] = '100';
$pattern['de'] = '100';
$pattern['do'] = '100';
$pattern['di'] = '100';
$pattern['du'] = '100';
$pattern['fa'] = '100';
$pattern['fe'] = '100';
$pattern['fo'] = '100';
$pattern['fi'] = '100';
$pattern['fu'] = '100';
$pattern['ga'] = '100';
$pattern['ge'] = '100';
$pattern['go'] = '100';
$pattern['gi'] = '100';
$pattern['gu'] = '100';
$pattern['ja'] = '100';
$pattern['je'] = '100';
$pattern['jo'] = '100';
$pattern['ji'] = '100';
$pattern['ju'] = '100';
$pattern['ka'] = '100';
$pattern['ke'] = '100';
$pattern['ko'] = '100';
$pattern['ki'] = '100';
$pattern['ku'] = '100';
$pattern['la'] = '100';
$pattern['le'] = '100';
$pattern['lo'] = '100';
$pattern['li'] = '100';
$pattern['lu'] = '100';
$pattern['ma'] = '100';
$pattern['me'] = '100';
$pattern['mo'] = '100';
$pattern['mi'] = '100';
$pattern['mu'] = '100';
$pattern['na'] = '100';
$pattern['ne'] = '100';
$pattern['no'] = '100';
$pattern['ni'] = '100';
$pattern['nu'] = '100';
$pattern['pa'] = '100';
$pattern['pe'] = '100';
$pattern['po'] = '100';
$pattern['pi'] = '100';
$pattern['pu'] = '100';
$pattern['qa'] = '100';
$pattern['qe'] = '100';
$pattern['qo'] = '100';
$pattern['qi'] = '100';
$pattern['qu'] = '100';
$pattern['ra'] = '100';
$pattern['re'] = '100';
$pattern['ro'] = '100';
$pattern['ri'] = '100';
$pattern['ru'] = '100';
$pattern['sa'] = '100';
$pattern['se'] = '100';
$pattern['so'] = '100';
$pattern['si'] = '100';
$pattern['su'] = '100';
$pattern['ta'] = '100';
$pattern['te'] = '100';
$pattern['to'] = '100';
$pattern['ti'] = '100';
$pattern['tu'] = '100';
$pattern['va'] = '100';
$pattern['ve'] = '100';
$pattern['vo'] = '100';
$pattern['vi'] = '100';
$pattern['vu'] = '100';
$pattern['wa'] = '100';
$pattern['we'] = '100';
$pattern['wo'] = '100';
$pattern['wi'] = '100';
$pattern['wu'] = '100';
$pattern['xa'] = '100';
$pattern['xe'] = '100';
$pattern['xo'] = '100';
$pattern['xi'] = '100';
$pattern['xu'] = '100';
$pattern['ya'] = '100';
$pattern['ye'] = '100';
$pattern['yo'] = '100';
$pattern['yi'] = '100';
$pattern['yu'] = '100';
$pattern['za'] = '100';
$pattern['ze'] = '100';
$pattern['zo'] = '100';
$pattern['zi'] = '100';
$pattern['zu'] = '100';
$pattern['lla'] = '10200';
$pattern['lle'] = '10200';
$pattern['llo'] = '10200';
$pattern['lli'] = '10200';
$pattern['llu'] = '10200';
$pattern['rra'] = '10200';
$pattern['rre'] = '10200';
$pattern['rro'] = '10200';
$pattern['rri'] = '10200';
$pattern['rru'] = '10200';
$pattern['tsa'] = '10200';
$pattern['tse'] = '10200';
$pattern['tso'] = '10200';
$pattern['tsi'] = '10200';
$pattern['tsu'] = '10200';
$pattern['txa'] = '10200';
$pattern['txe'] = '10200';
$pattern['txo'] = '10200';
$pattern['txi'] = '10200';
$pattern['txu'] = '10200';
$pattern['tza'] = '10200';
$pattern['tze'] = '10200';
$pattern['tzo'] = '10200';
$pattern['tzi'] = '10200';
$pattern['tzu'] = '10200';
$pattern['bla'] = '10200';
$pattern['ble'] = '10200';
$pattern['blo'] = '10200';
$pattern['bli'] = '10200';
$pattern['blu'] = '10200';
$pattern['bra'] = '10200';
$pattern['bre'] = '10200';
$pattern['bro'] = '10200';
$pattern['bri'] = '10200';
$pattern['bru'] = '10200';
$pattern['dra'] = '10200';
$pattern['dre'] = '10200';
$pattern['dro'] = '10200';
$pattern['dri'] = '10200';
$pattern['dru'] = '10200';
$pattern['fla'] = '10200';
$pattern['fle'] = '10200';
$pattern['flo'] = '10200';
$pattern['fli'] = '10200';
$pattern['flu'] = '10200';
$pattern['fra'] = '10200';
$pattern['fre'] = '10200';
$pattern['fro'] = '10200';
$pattern['fri'] = '10200';
$pattern['fru'] = '10200';
$pattern['gla'] = '10200';
$pattern['gle'] = '10200';
$pattern['glo'] = '10200';
$pattern['gli'] = '10200';
$pattern['glu'] = '10200';
$pattern['gra'] = '10200';
$pattern['gre'] = '10200';
$pattern['gro'] = '10200';
$pattern['gri'] = '10200';
$pattern['gru'] = '10200';
$pattern['kla'] = '10200';
$pattern['kle'] = '10200';
$pattern['klo'] = '10200';
$pattern['kli'] = '10200';
$pattern['klu'] = '10200';
$pattern['kra'] = '10200';
$pattern['kre'] = '10200';
$pattern['kro'] = '10200';
$pattern['kri'] = '10200';
$pattern['kru'] = '10200';
$pattern['pla'] = '10200';
$pattern['ple'] = '10200';
$pattern['plo'] = '10200';
$pattern['pli'] = '10200';
$pattern['plu'] = '10200';
$pattern['pra'] = '10200';
$pattern['pre'] = '10200';
$pattern['pro'] = '10200';
$pattern['pri'] = '10200';
$pattern['pru'] = '10200';
$pattern['tra'] = '10200';
$pattern['tre'] = '10200';
$pattern['tro'] = '10200';
$pattern['tri'] = '10200';
$pattern['tru'] = '10200';
$pattern['subr'] = '002020';
$pattern['subl'] = '002020';
?>