<?php
/**
 * $Id$
 *
 * Copyright (c) 2008-2010 Andreas Heigl<andreas@heigl.org>
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 * THE SOFTWARE.
 *
 * This file has been automaticly created from the file fihyph.tex
 * via the method Org_Heigl_Hyphenator::parseTexFile().
 *
 * DO NOT EDIT THIS FILE EXCEPT YOU KNOW WHAT YOU DO!!
 *
 * @category   Org_Heigl
 * @package    Org_Heigl_Hyphenator
 * @subpackage HyphenationFiles
 * @author     Org_Heigl_Hyphenator
 * @copyright  2008-2010 Andreas Heigl<andreas@heigl.org>
 * @license    http://www.opensource.org/licenses/mit-license.php MIT-License
 * @version    1.0
 * @since      12.09.2011
 */
$pattern['ba'] = '100';
$pattern['be'] = '100';
$pattern['bi'] = '100';
$pattern['bo'] = '100';
$pattern['bu'] = '100';
$pattern['by'] = '100';
$pattern['da'] = '100';
$pattern['de'] = '100';
$pattern['di'] = '100';
$pattern['do'] = '100';
$pattern['du'] = '100';
$pattern['dy'] = '100';
$pattern['d^^e'] = '100004';
$pattern['d^^f'] = '100006';
$pattern['fa'] = '100';
$pattern['fe'] = '100';
$pattern['fi'] = '100';
$pattern['fo'] = '100';
$pattern['fu'] = '100';
$pattern['fy'] = '100';
$pattern['ga'] = '100';
$pattern['ge'] = '100';
$pattern['gi'] = '100';
$pattern['go'] = '100';
$pattern['gu'] = '100';
$pattern['gy'] = '100';
$pattern['g^^e'] = '100004';
$pattern['g^^f'] = '100006';
$pattern['ha'] = '100';
$pattern['he'] = '100';
$pattern['hi'] = '100';
$pattern['ho'] = '100';
$pattern['hu'] = '100';
$pattern['hy'] = '100';
$pattern['h^^e'] = '100004';
$pattern['h^^f'] = '100006';
$pattern['ja'] = '100';
$pattern['je'] = '100';
$pattern['ji'] = '100';
$pattern['jo'] = '100';
$pattern['ju'] = '100';
$pattern['jy'] = '100';
$pattern['j^^e'] = '100004';
$pattern['j^^f'] = '100006';
$pattern['ka'] = '100';
$pattern['ke'] = '100';
$pattern['ki'] = '100';
$pattern['ko'] = '100';
$pattern['ku'] = '100';
$pattern['ky'] = '100';
$pattern['k^^e'] = '100004';
$pattern['k^^f'] = '100006';
$pattern['la'] = '100';
$pattern['le'] = '100';
$pattern['li'] = '100';
$pattern['lo'] = '100';
$pattern['lu'] = '100';
$pattern['ly'] = '100';
$pattern['l^^e'] = '100004';
$pattern['l^^f'] = '100006';
$pattern['ma'] = '100';
$pattern['me'] = '100';
$pattern['mi'] = '100';
$pattern['mo'] = '100';
$pattern['mu'] = '100';
$pattern['my'] = '100';
$pattern['m^^e'] = '100004';
$pattern['m^^f'] = '100006';
$pattern['na'] = '100';
$pattern['ne'] = '100';
$pattern['ni'] = '100';
$pattern['no'] = '100';
$pattern['nu'] = '100';
$pattern['ny'] = '100';
$pattern['n^^e'] = '100004';
$pattern['n^^f'] = '100006';
$pattern['pa'] = '100';
$pattern['pe'] = '100';
$pattern['pi'] = '100';
$pattern['po'] = '100';
$pattern['pu'] = '100';
$pattern['py'] = '100';
$pattern['p^^e'] = '100004';
$pattern['p^^f'] = '100006';
$pattern['ra'] = '100';
$pattern['re'] = '100';
$pattern['ri'] = '100';
$pattern['ro'] = '100';
$pattern['ru'] = '100';
$pattern['ry'] = '100';
$pattern['r^^e'] = '100004';
$pattern['r^^f'] = '100006';
$pattern['sa'] = '100';
$pattern['se'] = '100';
$pattern['si'] = '100';
$pattern['so'] = '100';
$pattern['su'] = '100';
$pattern['sy'] = '100';
$pattern['s^^e'] = '100004';
$pattern['s^^f'] = '100006';
$pattern['ta'] = '100';
$pattern['te'] = '100';
$pattern['ti'] = '100';
$pattern['to'] = '100';
$pattern['tu'] = '100';
$pattern['ty'] = '100';
$pattern['t^^e'] = '100004';
$pattern['t^^f'] = '100006';
$pattern['va'] = '100';
$pattern['ve'] = '100';
$pattern['vi'] = '100';
$pattern['vo'] = '100';
$pattern['vu'] = '100';
$pattern['vy'] = '100';
$pattern['v^^e'] = '100004';
$pattern['v^^f'] = '100006';
$pattern['str'] = '10020';
$pattern['^^ey'] = '000420';
$pattern['ya'] = '0102';
$pattern['yo'] = '0102';
$pattern['oy'] = '010';
$pattern['^^fy'] = '000620';
$pattern['uy'] = '0102';
$pattern['yu'] = '0102';
$pattern['^^fa'] = '0006302';
$pattern['^^fo'] = '0006302';
$pattern['^^ea'] = '0004302';
$pattern['^^eo'] = '0004302';
$pattern['^^eu'] = '0004102';
$pattern['^^fu'] = '0006102';
$pattern['a^^e'] = '010004';
$pattern['a^^f'] = '010006';
$pattern['o^^e'] = '010004';
$pattern['o^^f'] = '010006';
$pattern['u^^e'] = '0100042';
$pattern['u^^f'] = '0100062';
$pattern['^^e^^e'] = '000420004';
$pattern['^^f^^f'] = '000620006';
$pattern['^^e^^f'] = '000420006';
$pattern['^^f^^e'] = '000620004';
$pattern['aai'] = '00102';
$pattern['aae'] = '00102';
$pattern['aao'] = '00102';
$pattern['aau'] = '00102';
$pattern['eea'] = '00102';
$pattern['eei'] = '00102';
$pattern['eeu'] = '00102';
$pattern['eey'] = '00102';
$pattern['iia'] = '00102';
$pattern['iie'] = '00102';
$pattern['iio'] = '00102';
$pattern['uua'] = '00102';
$pattern['uue'] = '00102';
$pattern['uuo'] = '00102';
$pattern['uui'] = '00102';
$pattern['eaa'] = '0100';
$pattern['iaa'] = '0100';
$pattern['oaa'] = '0100';
$pattern['uaa'] = '0100';
$pattern['uee'] = '0100';
$pattern['auu'] = '0100';
$pattern['iuu'] = '0100';
$pattern['euu'] = '0100';
$pattern['ouu'] = '0100';
$pattern['^^e^^ei'] = '0004000410';
$pattern['^^e^^ee'] = '0004000410';
$pattern['^^e^^ey'] = '0004000430';
$pattern['i^^e^^e'] = '0100040004';
$pattern['e^^e^^e'] = '0100040004';
$pattern['y^^e^^e'] = '0100040004';
$pattern['i^^f^^f'] = '0100060006';
$pattern['aei'] = '0100';
$pattern['aoi'] = '0100';
$pattern['eai'] = '0100';
$pattern['iau'] = '0100';
$pattern['yei'] = '0100';
$pattern['aia'] = '0010';
$pattern['aie'] = '0010';
$pattern['aio'] = '0010';
$pattern['aiu'] = '0010';
$pattern['aua'] = '0010';
$pattern['aue'] = '0010';
$pattern['eua'] = '0010';
$pattern['iea'] = '0010';
$pattern['ieo'] = '0010';
$pattern['iey'] = '0010';
$pattern['ioa'] = '00102';
$pattern['ioe'] = '00102';
$pattern['iua'] = '0010';
$pattern['iue'] = '0010';
$pattern['iuo'] = '0010';
$pattern['oia'] = '0010';
$pattern['oie'] = '0010';
$pattern['oio'] = '0010';
$pattern['oiu'] = '0010';
$pattern['oui'] = '0100';
$pattern['oue'] = '0010';
$pattern['ouo'] = '0010';
$pattern['uea'] = '0010';
$pattern['uie'] = '0010';
$pattern['uoa'] = '0010';
$pattern['uou'] = '0010';
$pattern['e^^f'] = '0100062';
$pattern['^^fe'] = '0006102';
$pattern['_^^e'] = '000042';
$pattern['us'] = '020';
$pattern['yliop'] = '0001020';
$pattern['aliav'] = '0001020';
$pattern['spli'] = '100200';
$pattern['alous'] = '000001';
$pattern['keus'] = '00001';
$pattern['rtaus'] = '000001';
$pattern['sohje'] = '2010000';
$pattern['sasia'] = '20102000';
$pattern['asian'] = '1020000';
$pattern['asiat'] = '1020000';
$pattern['asioi'] = '1020000';
$pattern['ras'] = '0200';
$pattern['las'] = '0200';
$pattern['sopisk'] = '201020000';
$pattern['nopet'] = '20102000';
$pattern['saloi'] = '20102000';
$pattern['nopist'] = '201020000';
$pattern['sopist'] = '201020000';
$pattern['sosa'] = '2010200';
$pattern['nosa'] = '2010200';
$pattern['alkeis'] = '00000201';
$pattern['perus'] = '000001';
$pattern['sidea_'] = '201020000';
$pattern['sidean'] = '201020000';
$pattern['sesity'] = '201020000';
$pattern['nedus'] = '20102000';
$pattern['sajatu'] = '20100000';
$pattern['sase'] = '201000';
$pattern['sapu'] = '201000';
$pattern['syrit'] = '20102000';
$pattern['_ydin'] = '0000201';
$pattern['_suura'] = '000020102';
$pattern['syhti'] = '20102000';
$pattern['notto'] = '2010000';
$pattern['noton'] = '2010000';
$pattern['nanto'] = '2010000';
$pattern['nanno'] = '2010000';
$pattern['najan'] = '20102000';
$pattern['naika'] = '2010000';
$pattern['nomai'] = '20102000';
$pattern['nylit'] = '20102000';
$pattern['salen'] = '20102000';
$pattern['nalen'] = '20102000';
$pattern['asiakas'] = '10200000201';
$pattern['ulos'] = '000201';
$pattern['najo'] = '2010200';
$pattern['sajo'] = '2010200';
$pattern['bl'] = '020';
$pattern['blo'] = '10200';
$pattern['bibli'] = '000300';
$pattern['br'] = '020';
$pattern['bri'] = '10200';
$pattern['bro'] = '10200';
$pattern['bru'] = '10200';
$pattern['dr'] = '020';
$pattern['dra'] = '10200';
$pattern['fl'] = '020';
$pattern['fla'] = '10200';
$pattern['fr'] = '020';
$pattern['fra'] = '10200';
$pattern['fre'] = '10200';
$pattern['gl'] = '020';
$pattern['glo'] = '10200';
$pattern['gr'] = '020';
$pattern['gra'] = '10200';
$pattern['kl'] = '020';
$pattern['kra'] = '10200';
$pattern['kre'] = '10200';
$pattern['kri'] = '10200';
$pattern['kv'] = '1020';
$pattern['kva'] = '10200';
$pattern['pl'] = '020';
$pattern['pr'] = '020';
$pattern['pro'] = '10200';
$pattern['cl'] = '020';
$pattern['qv'] = '020';
$pattern['qvi'] = '10200';
$pattern['sch'] = '0020';
$pattern['tsh'] = '0020';
$pattern['chr'] = '0020';
?>