<?php
/**
 * $Id$
 *
 * Copyright (c) 2008-2010 Andreas Heigl<andreas@heigl.org>
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 * THE SOFTWARE.
 *
 * This file has been automaticly created from the file inhyph.tex
 * via the method Org_Heigl_Hyphenator::parseTexFile().
 *
 * DO NOT EDIT THIS FILE EXCEPT YOU KNOW WHAT YOU DO!!
 *
 * @category   Org_Heigl
 * @package    Org_Heigl_Hyphenator
 * @subpackage HyphenationFiles
 * @author     Org_Heigl_Hyphenator
 * @copyright  2008-2010 Andreas Heigl<andreas@heigl.org>
 * @license    http://www.opensource.org/licenses/mit-license.php MIT-License
 * @version    1.0
 * @since      12.09.2011
 */
$pattern['a'] = '01';
$pattern['e'] = '01';
$pattern['i'] = '01';
$pattern['o'] = '01';
$pattern['u'] = '01';
$pattern['bd'] = '2010';
$pattern['bj'] = '2010';
$pattern['bk'] = '2010';
$pattern['bn'] = '2010';
$pattern['bs'] = '2010';
$pattern['bt'] = '2010';
$pattern['ck'] = '2010';
$pattern['cn'] = '2010';
$pattern['dk'] = '2010';
$pattern['dn'] = '2010';
$pattern['dp'] = '2010';
$pattern['fd'] = '2010';
$pattern['fk'] = '2010';
$pattern['fn'] = '2010';
$pattern['ft'] = '2010';
$pattern['gg'] = '2010';
$pattern['gk'] = '2010';
$pattern['gn'] = '2010';
$pattern['hk'] = '2010';
$pattern['hl'] = '2010';
$pattern['hm'] = '2010';
$pattern['hn'] = '2010';
$pattern['hw'] = '2010';
$pattern['jk'] = '2010';
$pattern['jn'] = '2010';
$pattern['kb'] = '2010';
$pattern['kk'] = '2010';
$pattern['km'] = '2010';
$pattern['kn'] = '2010';
$pattern['kr'] = '2010';
$pattern['ks'] = '2010';
$pattern['kt'] = '2010';
$pattern['lb'] = '2010';
$pattern['lf'] = '2010';
$pattern['lg'] = '2010';
$pattern['lh'] = '2010';
$pattern['lk'] = '2010';
$pattern['lm'] = '2010';
$pattern['ln'] = '2010';
$pattern['ls'] = '2010';
$pattern['lt'] = '2010';
$pattern['lq'] = '2010';
$pattern['mb'] = '2010';
$pattern['mk'] = '2010';
$pattern['ml'] = '2010';
$pattern['mm'] = '2010';
$pattern['mn'] = '2010';
$pattern['mp'] = '2010';
$pattern['mr'] = '2010';
$pattern['ms'] = '2010';
$pattern['nc'] = '2010';
$pattern['nd'] = '2010';
$pattern['nf'] = '2010';
$pattern['nj'] = '2010';
$pattern['nk'] = '2010';
$pattern['nn'] = '2010';
$pattern['np'] = '2010';
$pattern['ns'] = '2010';
$pattern['nt'] = '2010';
$pattern['nv'] = '2010';
$pattern['pk'] = '2010';
$pattern['pn'] = '2010';
$pattern['pp'] = '2010';
$pattern['pr'] = '2010';
$pattern['pt'] = '2010';
$pattern['rb'] = '2010';
$pattern['rc'] = '2010';
$pattern['rf'] = '2010';
$pattern['rg'] = '2010';
$pattern['rh'] = '2010';
$pattern['rj'] = '2010';
$pattern['rk'] = '2010';
$pattern['rl'] = '2010';
$pattern['rm'] = '2010';
$pattern['rn'] = '2010';
$pattern['rp'] = '2010';
$pattern['rr'] = '2010';
$pattern['rs'] = '2010';
$pattern['rt'] = '2010';
$pattern['rw'] = '2010';
$pattern['ry'] = '2010';
$pattern['sb'] = '2010';
$pattern['sk'] = '2010';
$pattern['sl'] = '2010';
$pattern['sm'] = '2010';
$pattern['sn'] = '2010';
$pattern['sp'] = '2010';
$pattern['sr'] = '2010';
$pattern['ss'] = '2010';
$pattern['st'] = '2010';
$pattern['sw'] = '2010';
$pattern['tk'] = '2010';
$pattern['tl'] = '2010';
$pattern['tn'] = '2010';
$pattern['tt'] = '2010';
$pattern['wt'] = '2010';
$pattern['ngg'] = '20010';
$pattern['ngh'] = '20010';
$pattern['ngk'] = '20010';
$pattern['ngn'] = '20010';
$pattern['ngs'] = '20010';
$pattern['nst'] = '203020';
$pattern['_ber'] = '000203';
$pattern['_ter'] = '000203';
$pattern['_meng'] = '0002003';
$pattern['_per'] = '000203';
$pattern['ng_'] = '2000';
$pattern['ny_'] = '2000';
$pattern['ion'] = '02010';
$pattern['air'] = '0200';
$pattern['bagai'] = '10010020';
$pattern['ban_'] = '201000';
$pattern['can_'] = '201000';
$pattern['dan_'] = '201000';
$pattern['fan_'] = '201000';
$pattern['gan_'] = '201000';
$pattern['han_'] = '201000';
$pattern['jan_'] = '201000';
$pattern['kan_'] = '201000';
$pattern['lan_'] = '201000';
$pattern['man_'] = '201000';
$pattern['ngan_'] = '2001000';
$pattern['nan_'] = '201000';
$pattern['pan_'] = '201000';
$pattern['ran_'] = '201000';
$pattern['san_'] = '201000';
$pattern['tan_'] = '201000';
$pattern['van_'] = '201000';
$pattern['zan_'] = '201000';
$pattern['an_'] = '3000';
$pattern['_atau'] = '0020020';
$pattern['_tangan_'] = '0003004000';
$pattern['_lengan_'] = '0003004000';
$pattern['_jangan_'] = '0003004000';
$pattern['_mangan_'] = '0003004000';
$pattern['_pangan_'] = '0003004000';
$pattern['_ringan_'] = '0003004000';
$pattern['_dengan_'] = '0003004000';
$pattern['}'] = '0';
$pattern['be-ra-hi'] = '00000000';
$pattern['be-rak'] = '000000';
$pattern['be-ran-da'] = '000000000';
$pattern['be-ran-dal'] = '0000000000';
$pattern['be-rang'] = '0000000';
$pattern['be-ra-ngas-an'] = '0000000000000';
$pattern['be-rang-sang'] = '000000000000';
$pattern['be-ra-ngus'] = '0000000000';
$pattern['be-ra-ni'] = '00000000';
$pattern['be-ran-tak-an'] = '0000000000000';
$pattern['be-ran-tam'] = '0000000000';
$pattern['be-ran-tas'] = '0000000000';
$pattern['be-ra-pa'] = '00000000';
$pattern['be-ras'] = '000000';
$pattern['be-ren-deng'] = '00000000000';
$pattern['be-re-ngut'] = '0000000000';
$pattern['be-re-rot'] = '000000000';
$pattern['be-res'] = '000000';
$pattern['be-re-wok'] = '000000000';
$pattern['be-ri'] = '00000';
$pattern['be-ri-ngas'] = '0000000000';
$pattern['be-ri-sik'] = '000000000';
$pattern['be-ri-ta'] = '00000000';
$pattern['be-rok'] = '000000';
$pattern['be-ron-dong'] = '00000000000';
$pattern['be-ron-tak'] = '0000000000';
$pattern['be-ru-du'] = '00000000';
$pattern['be-ruk'] = '000000';
$pattern['be-run-tun'] = '0000000000';
$pattern['peng-eks-por'] = '000000000000';
$pattern['peng-im-por'] = '00000000000';
$pattern['te-ra'] = '00000';
$pattern['te-rang'] = '0000000';
$pattern['te-ras'] = '000000';
$pattern['te-ra-si'] = '00000000';
$pattern['te-ra-tai'] = '000000000';
$pattern['te-ra-wang'] = '0000000000';
$pattern['te-ra-weh'] = '000000000';
$pattern['te-ri-ak'] = '00000000';
$pattern['te-ri-gu'] = '00000000';
$pattern['te-rik'] = '000000';
$pattern['te-ri-ma'] = '00000000';
$pattern['te-ri-pang'] = '0000000000';
$pattern['te-ro-bos'] = '000000000';
$pattern['te-ro-bos-an'] = '000000000000';
$pattern['te-ro-mol'] = '000000000';
$pattern['te-rom-pah'] = '0000000000';
$pattern['te-rom-pet'] = '0000000000';
$pattern['te-ro-pong'] = '0000000000';
$pattern['te-ro-wong-an'] = '0000000000000';
$pattern['te-ru-buk'] = '000000000';
$pattern['te-ru-na'] = '00000000';
$pattern['te-rus'] = '000000';
$pattern['te-ru-si'] = '00000000';
?>