#!/usr/bin/env php
<?php
namespace Org\Heigl\Hyphenator\Dictionary;

require_once __DIR__ . '/../vendor/autoload.php';

$share = realpath(__DIR__ . '/../src/share/files/dictionaries');

$iterator = new \DirectoryIterator($share);
Dictionary::setFileLocation(__DIR__ . '/../src/share/files/dictionaries');
foreach ( $iterator as $file ) {
    if ( ! preg_match('/hyph_([\w\_]+)\.dic/',$file->getFileName(),$result) ) {
        continue;
    }
    echo "\n" . 'rendering ' . $result[1] . ' in ';
    
    $time = microtime(true);
    try{
        Dictionary::parseFile($result[1]);
    }catch(\Exception $e){}
    echo round(microtime(true)-$time,5) . ' seconds' . "\n";
}
