name: Build
on: [push, pull_request]
permissions: {}
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true
jobs:
  check:
    name: Run CodeStyle checks
    runs-on: ubuntu-latest
    continue-on-error: false
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 #7.0.1
        with:
          persist-credentials: false
      - name: Setup PHP
        uses: shivammathur/setup-php@f3e473d116dcccaddc5834248c87452386958240 # 2.37.2
        with:
          php-version: "8.5"
          tools: phive
      - name: Download codesniffer
        run: phive --no-progress install --trust-gpg-keys 31C7E470E2138192,5E6DDE998AB73B8E,97B02DD8E5071466 phpcs
      - name: check
        run: ./tools/phpcs
  test:
    name: Test with PHP ${{ matrix.php-versions }}
    needs: check
    runs-on: ubuntu-latest # ${{ matrix.operating-system }}
    continue-on-error: ${{ matrix.experimental }}
    strategy:
      matrix:
        # operating-system: [ubuntu-latest, windows-latest, macos-latest]
        php-versions: ['7.2', '7.3', '7.4', '8.0', '8.1', '8.2', '8.3', '8.4', '8.5']
        experimental: [false]
        include:
          - php-versions: '8.6'
            experimental: true
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 #7.0.1
        with:
          persist-credentials: false
      - name: Setup PHP
        uses: shivammathur/setup-php@f3e473d116dcccaddc5834248c87452386958240 #2.37.2
        with:
          php-version: ${{ matrix.php-versions }}
          extensions: sodium
          ini-values: post_max_size=256M, short_open_tag=On
          coverage: xdebug
      - name: prepare
        run: composer update
      - name: test
        run: composer test
  analyze:
    name: Static analysis
    needs: test
    runs-on: ubuntu-latest
    continue-on-error: false
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # 7.0.1
        with:
          persist-credentials: false
      - name: Setup PHP
        uses: shivammathur/setup-php@f3e473d116dcccaddc5834248c87452386958240 #2.37.2
        with:
          php-version: "8.4"
      - name: install
        run: composer install
      - name: analyze
        run: ./vendor/bin/phpstan
  coverage:
    name: Code-Coverage
    needs: test
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    continue-on-error: false
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 #7.0.1
        with:
          persist-credentials: false
      - name: Setup PHP
        uses: shivammathur/setup-php@f3e473d116dcccaddc5834248c87452386958240 #2.37.2
        with:
          php-version: "8.5"
          coverage: xdebug
      - name: Install
        run: composer update
      - name: run testsuite
        run: composer test-coverage
      - name: Upload coverage results to Coveralls
        env:
          COVERALLS_REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          composer global require php-coveralls/php-coveralls
          php-coveralls --coverage_clover=clover.xml -v
